Add dependency injection [001]
Lezzess/Darts.FrontEnd.Mobile pull request #1
Opened 2020-12-07 13:39 UTC by Lezzess

2020-12-07 13:40 UTC, Lezzess commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add dependency injection [001]](https://trello.com/c/i5QqfzWC/3-add-dependency-injection-001)

2020-12-13 19:39 UTC, ATL-95 commented on src/Database/DependencyInjection/Dependencies.cs
> +
We could use throw new NotImplementedException() until methods not implemented, i think it is a good behavior

2020-12-13 19:43 UTC, ATL-95 commented on src/UserInterface/UserInterface.Android/MainActivity.cs
> +        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
If Permission class do not conflict with another class in another library, please add reference to it in top.

2020-12-13 19:46 UTC, ATL-95 commented on src/UserInterface/UserInterface.Android/UserInterface.Android.csproj
> +      <UserProperties TriggeredFromHotReload="False" />
We will need be on this function for active development

2020-12-13 19:53 UTC, ATL-95 requested changes
You need look my comments and if you have different opinion we will need discussed it.

2020-12-19 10:42 UTC, Lezzess commented on src/Database/DependencyInjection/Dependencies.cs
> +
Exception will crash the application

2020-12-19 11:09 UTC, Lezzess commented on src/UserInterface/UserInterface.Android/UserInterface.Android.csproj
> +      <UserProperties TriggeredFromHotReload="False" />
I don't know what this property is for but hot reload works for me even with it being False.
It was autogenerated by Visual Studio so I did not change anything

2020-12-27 22:19 UTC, ATL-95 approved these changes

2020-12-27 22:19 UTC, merged